export const USER_ACTION_TYPES= {
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_UP_USER_START: 'SIGN_UP_USER_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
    SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
    SIGN_OUT_USER_FAILURE: 'SIGN_OUT_USER_FAILURE'
}