
export const CATEGORIES_ACTION_TYPES= {
    FECTH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCESS: 'FETCH_CATEGORIES_SUCESS',
    FETCH_CATEGORIES_FAILED: 'FETCH_CATEGORIES_FAILED',
}